### ISSUE TITLE
User is always null

### ISSUE THREAD

**Issue by goran-paunovic** [Devtools-Tech-Team/remix-run-social-authentication-example#2]
Followed instructions in readme.
When I start the app and do the Google authentication, cookie is created but nothing changed in the app.
Button text is still "Login with Google".

**Comment by yomeshgupta** [comment]
1. Did you make any changes to the codebase?
2. Did you add your own `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET`?

I would recommend taking the latest pull and trying again once. @goran-paunovic

**Comment by goran-paunovic** [comment]
1. The only change I made was to add dotenv since I am on windows
2. Yes, I added my own environment variables
I pulled the latest code and it's same story.
When user is redirected to dashboard page it is being redirected to index page because authenticator.isAuthenticated is failing.

https://www.loom.com/share/dc1299ad47484a7796e44b29b1c202a0

![image](https://user-images.githubusercontent.com/8568410/159807022-f99058df-dd3e-4bed-9592-842e3f7488a7.png)

**Comment by edmondchuc** [comment]
For what it's worth, I just tried the repo on Windows in WSL2 and it worked fine for me.

**Comment by yomeshgupta** [comment]
@goran-paunovic Sorry, I don't have access to a Windows system as of now so can't really test this. I would suggest try updating the action below

https://github.com/Devtools-Tech-Team/remix-run-social-authentication-example/blob/aa84581b41d9a0b36f741215918820274be94f2e/app/routes/auth.google.jsx#L4

and see if there is an error

```js
export const action = async ({ request }) => {
  try {
    await authenticator.authenticate(SocialsProvider.GOOGLE, request, {
      successRedirect: "/dashboard",
      throwOnError: true
    });
  } catch (err) {
    console.log(err);
  }
};
```

Let me know how it goes.

**Comment by goran-paunovic** [comment]
```
Error: Route "routes/auth.google" has no component! Please go add a `default` export in the route module file.
If you were trying to navigate or submit to a resource route, use `<a>` instead of `<Link>` or `<Form reloadDocument>`.
    at DefaultRouteComponent (http://localhost:5555/build/_shared/chunk-YICEDRTK.js:3057:9)
    at renderWithHooks (http://localhost:5555/build/entry.client-AGSGTYCG.js:11071:26)
    at mountIndeterminateComponent (http://localhost:5555/build/entry.client-AGSGTYCG.js:13191:21)
    at beginWork (http://localhost:5555/build/entry.client-AGSGTYCG.js:13978:22)
    at HTMLUnknownElement.callCallback2 (http://localhost:5555/build/entry.client-AGSGTYCG.js:3681:22)
    at Object.invokeGuardedCallbackDev (http://localhost:5555/build/entry.client-AGSGTYCG.js:3706:24)
    at invokeGuardedCallback (http://localhost:5555/build/entry.client-AGSGTYCG.js:3740:39)
    at beginWork$1 (http://localhost:5555/build/entry.client-AGSGTYCG.js:17087:15)
    at performUnitOfWork (http://localhost:5555/build/entry.client-AGSGTYCG.js:16315:20)
    at workLoopSync (http://localhost:5555/build/entry.client-AGSGTYCG.js:16269:13)
```

**Comment by goran-paunovic** [comment]
> For what it's worth, I just tried the repo on Windows in WSL2 and it worked fine for me.

Tried it in WSL2 and it does not work for me.
